name: My1

on:   
  push:
    branches: [work]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v3.1.4
        with:
          python-version: 3.11
        
      - name: Install python dependencies
        run: pip install polib

      - name: Validate po and JSON files for hidden unicode
        run: python scripts/sneakyunicode.py
